-- MySQL Script generated by MySQL Workbench
-- 09/20/16 03:30:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online_exam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `online_exam` ;

-- -----------------------------------------------------
-- Schema online_exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_exam` DEFAULT CHARACTER SET utf8 ;
USE `online_exam` ;

-- -----------------------------------------------------
-- Table `online_exam`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`login` (
  `email` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`, `password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`teacher` (
  `name` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL,
  `university_name` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `login_email` INT NOT NULL,
  `login_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `login_email`, `login_password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`question_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`question_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `descriptions` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`section` (
  `id` INT NOT NULL,
  `number_question` VARCHAR(45) NOT NULL,
  `Time_section` TIMESTAMP(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`question` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `number_answer` INT NOT NULL,
  `number_question_true` INT NOT NULL,
  `category_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `section_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`exam` (
  `id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `question_question_category_id` INT NOT NULL,
  `question_section_id` INT NOT NULL,
  PRIMARY KEY (`id`, `question_id`, `question_question_category_id`, `question_section_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`student_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`student_exam` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`student` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `studentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`result` (
  `student_id` INT NOT NULL,
  `exam_id` INT NOT NULL,
  `exam_teacher_id` INT NOT NULL,
  `exam_question_id` INT NOT NULL,
  `exam_question_question_category_id` INT NOT NULL,
  `exam_question_section_id` INT NOT NULL,
  `exam_result_student_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `exam_id`, `exam_teacher_id`, `exam_question_id`, `exam_question_question_category_id`, `exam_question_section_id`, `exam_result_student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_exam`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_exam`.`answer` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NULL,
  `question_id` INT NOT NULL,
  `is_correct` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `question_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
